{pkgs, ...}: {
  home.packages = with pkgs;
    [
      azure-cli
      asciinema
      asciinema-agg
      btop
      bun
      cachix
      chafa
      charm-freeze
      cook-cli
      coreutils
      crush
      darwin.trash
      diagon
      difftastic
      eza
      fd
      fnlfmt
      gh-dash
      glow
      gnupg
      go
      google-cloud-sdk
      goreleaser
      graph-easy
      graphviz
      gum
      gws
      handy
      httpie
      sc-im
      imagemagick
      jdk
      jq
      jujutsu
      melt
      moonside
      nodejs
      ollama
      opencode
      openssl
      pastel
      pop
      redis
      ripgrep
      rustup
      sd
      serve
      skate
      skimpdf
      tdf
      tinymist
      tree-sitter
      ttyd
      pi-coding-agent
      typescript
      typioca
      typst
      vhs
      watchexec
      worktrunk
      yq
      zig
      zoxide
    ]
    # lsp
    ++ [
      alejandra
      bash-language-server
      dot-language-server
      eslint
      golangci-lint
      golangci-lint-langserver
      gopls
      lua-language-server
      nixpkgs-fmt
      prettier
      proselint
      revive
      taplo
      typescript-language-server
      vscode-langservers-extracted
      write-good
      yaml-language-server
    ];
}
